<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!-- <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild> -->
    <DocumentationFile>$(OutputPath)$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>


  <Target Name="CopyDocumentation" AfterTargets="Build">
    <Copy SourceFiles="$(DocumentationFile)" DestinationFolder="..\SharedDocs\SolutionDocumentations" />
  </Target>

  <ItemGroup>
    <PackageReference Include="Anthropic" Version="3.4.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="EPPlus" Version="7.5.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.23" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.3.0" />
    <PackageReference Include="MySql.Data" Version="9.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <PackageReference Include="ObjectsComparer" Version="1.4.1" />
    <PackageReference Include="OpenAI" Version="2.1.0" />
    <PackageReference Include="Oracle.ManagedDataAccess" Version="23.7.0" />
    <PackageReference Include="Polly" Version="8.5.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DynamicDashboardCommon\DynamicDashboardCommon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\Users\" />
    <Folder Include="Services\DataBaseSchema\NewFolder\" />
  </ItemGroup>

</Project>
