using System.Collections.Generic;

namespace DynamicDashboardCommon.Models
{
    /// <summary>
    /// Represents a dashboard template configuration.
    /// Templates define LAYOUT (positions, sizes) and GUIDANCE (AI context).
    /// Content (titles, descriptions, queries, chart types) is generated by LLM.
    /// </summary>
    public class DashboardTemplate
    {
        /// <summary>
        /// Unique identifier for the template
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Display name of the template
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Description of what the template provides
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Category of the template (Executive, Operations, Finance, Analytics, etc.)
        /// This is key for LLM to understand the target audience
        /// </summary>
        public string Category { get; set; }

        /// <summary>
        /// URL to the template thumbnail image
        /// </summary>
        public string ThumbnailUrl { get; set; }

        /// <summary>
        /// Total height of the canvas in grid rows
        /// </summary>
        public int TotalHeight { get; set; }

        /// <summary>
        /// AI guidance for this template type.
        /// Instructs LLM about target audience, focus areas, and what to avoid.
        /// </summary>
        public TemplateAIGuidance AIGuidance { get; set; }

        /// <summary>
        /// List of component slots defining LAYOUT ONLY (type + position).
        /// LLM generates the actual content for each slot.
        /// </summary>
        public List<TemplateComponentSlot> Components { get; set; } = new List<TemplateComponentSlot>();
    }

    /// <summary>
    /// AI guidance configuration for a template.
    /// Provides context to help LLM generate appropriate components.
    /// </summary>
    public class TemplateAIGuidance
    {
        /// <summary>
        /// Target audience for this dashboard.
        /// Examples: "C-level executives", "Operations managers", "Data analysts"
        /// </summary>
        public string TargetAudience { get; set; }

        /// <summary>
        /// Primary focus areas for this dashboard type.
        /// Examples: "Revenue trends", "Operational efficiency", "Real-time monitoring"
        /// </summary>
        public List<string> FocusAreas { get; set; } = new List<string>();

        /// <summary>
        /// Preferred time granularity for this audience.
        /// Examples: "monthly", "quarterly" for executives; "daily", "hourly" for operations
        /// </summary>
        public List<string> TimeGranularity { get; set; } = new List<string>();

        /// <summary>
        /// Patterns to avoid in this dashboard type.
        /// Examples: "Granular transaction details" for executives
        /// </summary>
        public List<string> AvoidPatterns { get; set; } = new List<string>();

        /// <summary>
        /// Additional free-form guidance text for the LLM.
        /// Provides extra context about what makes this dashboard type effective.
        /// </summary>
        public string AdditionalGuidance { get; set; }
    }

    /// <summary>
    /// Represents a component slot within a template.
    /// Defines ONLY the component type and grid position.
    /// LLM generates: title, description, query, chartType (for charts).
    /// </summary>
    public class TemplateComponentSlot
    {
        /// <summary>
        /// Slot number for ordering (1, 2, 3, ...)
        /// </summary>
        public int Slot { get; set; }

        /// <summary>
        /// Type of component: "kpi", "chart", "table"
        /// LLM will generate appropriate content based on type.
        /// For charts, LLM decides the best chart type (line, bar, pie, area, etc.)
        /// </summary>
        public string Type { get; set; }

        /// <summary>
        /// X position in the grid (0-11 for 12-column grid)
        /// </summary>
        public int GridX { get; set; }

        /// <summary>
        /// Y position in the grid (row number, starting from 0)
        /// </summary>
        public int GridY { get; set; }

        /// <summary>
        /// Width in grid columns (1-12)
        /// </summary>
        public int GridWidth { get; set; }

        /// <summary>
        /// Height in grid rows
        /// </summary>
        public int GridHeight { get; set; }
    }

    /// <summary>
    /// Container for all dashboard templates (used for JSON deserialization)
    /// </summary>
    public class DashboardTemplateCollection
    {
        /// <summary>
        /// List of available templates
        /// </summary>
        public List<DashboardTemplate> Templates { get; set; } = new List<DashboardTemplate>();
    }
}