<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!-- <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild> -->
    <DocumentationFile>$(OutputPath)$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>


  <Target Name="CopyDocumentation" AfterTargets="Build">
    <Copy SourceFiles="$(DocumentationFile)" DestinationFolder="..\SharedDocs\SolutionDocumentations" />
  </Target>
  
  
  <ItemGroup>
    <PackageReference Include="Blazored.Toast" Version="4.2.1" />
    <PackageReference Include="Chart.js" Version="3.7.1" />
    <PackageReference Include="ChartJs.Blazor.Fork" Version="2.0.2" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.11" PrivateAssets="all" />
    <PackageReference Include="Northwoods.GoJS" Version="3.0.19" />
    <PackageReference Include="System.Net.Http.Json" Version="9.0.3" />
    <PackageReference Include="System.Text.Json" Version="9.0.3" />
    <!-- MudBlazor - UI Components -->
    <PackageReference Include="MudBlazor" Version="7.15.0" />

    <!-- ApexCharts for Blazor -->
    <PackageReference Include="Blazor-ApexCharts" Version="3.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DynamicDashboardCommon\DynamicDashboardCommon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Pages\Report\" />
    <Folder Include="Services\" />
    <Folder Include="Utilities\" />
  </ItemGroup>

</Project>
