using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DynamicDashboardCommon.Models
{
    /// <summary>
    /// Represents a comparison between different SQL query results generated from natural language questions.
    /// </summary>
    public class QueryComparison
    {
        /// <summary>
        /// Gets or sets the database schema.
        /// </summary>
        public string DbSchema { get; set; }

        /// <summary>
        /// Gets or sets the natural language question.
        /// </summary>
        public string NaturalLanguageQuestion { get; set; }

        /// <summary>
        /// Gets or sets the SQL query generated by GPT.
        /// </summary>
        public string GptSqlQuery { get; set; }

        /// <summary>
        /// Gets or sets the SQL query generated by DeepSeek.
        /// </summary>
        public string DeepSeekSqlQuery { get; set; }

        /// <summary>
        /// Gets or sets the SQL query generated by DeepSeek Chat.
        /// </summary>
        public string DeepSeekChatSqlQuery { get; set; }

        /// <summary>
        /// Gets or sets the data result from the GPT SQL query.
        /// </summary>
        public List<Dictionary<string, object>> GptDataResult { get; set; }

        /// <summary>
        /// Gets or sets the data result from the DeepSeek SQL query.
        /// </summary>
        public List<Dictionary<string, object>> DeepSeekDataResult { get; set; }

        /// <summary>
        /// Gets or sets the data result from the DeepSeek Chat SQL query.
        /// </summary>
        public List<Dictionary<string, object>> DeepSeekChatDataResult { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the GPT result is compared with the DeepSeek Chat result.
        /// </summary>
        public bool GptVsDeepSeekChatComparison { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the DeepSeek result is compared with the DeepSeek Chat result.
        /// </summary>
        public bool DeepSeekVsDeepSeekChatComparison { get; set; }
    }
}
